### PR TITLE
fix: fix tiny line between arrow and popover

### PR DESCRIPTION
**Pull request by jaulz**
This PR fixes the tiny line between arrows and popovers. Before:
image

After:
image

### CODE REVIEW

**Comment by 07akioni** [comment]
I've tried it before. In my memory, antd doesn't have such problem. Maybe we can see how antd do it.

**Comment by jaulz** [comment]
I think they do something similar but just on a JavaScript level:
image

They also have a tiny difference:
image

**Comment by 07akioni** [comment]
> I think they do something similar but just on a JavaScript level: image
> 
> They also have a tiny difference: image

Can we apply their solution

**Comment by jaulz** [comment]
Having an even closer look:
image

I think distance is clear but the second part is unclear for me:
image

(see https://github.com/ant-design/ant-design/blob/master/components/tooltip/style/index.less)

**Comment by 07akioni** [comment]
The problem is fixed by using opaque background.

**Pull request closed without merging**
