### PR TITLE
feat(color-picker): support swatches

### PR DESCRIPTION
**Pull request by nooooooom**
* feat(color-picker): support swatches
ref [#1281](https://github.com/TuSimple/naive-ui/issues/1281)

### CODE REVIEW

**Comment by nooooooom** [comment]
> Sorry for reviewing late. I'm a bit busy in weekdays.

Thank you for taking the time to review this PR. (Your health is your most precious asset, please have a good rest!)
I have experience in developing color picker components, so I tried to do it. In fact, I did not consider a lot of details.
Thank you for your carefulness, which allows me to benefit from this PR. I am going to revise this PR based on your suggestion.

**Comment by 07akioni** [comment]
> Sorry, because the path where I opened the editor is incorrect, the submitted code has a format error, which has now been processed.
> 
> I will pay attention to such problems in the future (I thought it was caused by dependency).

don't worry, just fix it

**Comment by 07akioni** [comment]
> This pull request **introduces 1 alert** when merging [b633559](https://github.com/TuSimple/naive-ui/commit/b63355941a4567be9a526db55da000aaf9a67a7a) into [fb9beb6](https://github.com/TuSimple/naive-ui/commit/fb9beb6d3cdfae1c4f0a59177e72a957348cd961) - [view on LGTM.com](https://lgtm.com/projects/g/TuSimple/naive-ui/rev/pr-084eb048bb8b1e78287394355180edf7599d9d6d)
> 
> **new alerts:**
> 
> * 1 for Unneeded defensive code

Also see LGTM problem

**Comment by nooooooom** [comment]
> > This pull request **introduces 1 alert** when merging [b633559](https://github.com/TuSimple/naive-ui/commit/b63355941a4567be9a526db55da000aaf9a67a7a) into [fb9beb6](https://github.com/TuSimple/naive-ui/commit/fb9beb6d3cdfae1c4f0a59177e72a957348cd961) - [view on LGTM.com](https://lgtm.com/projects/g/TuSimple/naive-ui/rev/pr-084eb048bb8b1e78287394355180edf7599d9d6d)
> > **new alerts:**
> > 
> > * 1 for Unneeded defensive code
> 
> Also see LGTM problem

I will add test cases tomorrow!

**Pull request merged**
