### PR TITLE
revert: pr 2162

### PR DESCRIPTION
**Pull request by kungege**
ref [#2162](https://github.com/TuSimple/naive-ui/pull/2162)
image

### CODE REVIEW

**Review by amadeus711 — APPROVED** [review]

**Review by amadeus711 — CHANGES_REQUESTED** [review]
不应该在这里改，去申明变量的地方修改

**Comment by kungege** [comment]
> 不应该在这里改，去申明变量的地方修改

改变量会影响`.base-selection-input`以及`.base-selection-overlay`的样式

**Comment by jaulz** [comment]
(sorry, in case it was mentioned before but I don't understand Chinese 😊 )

Instead of reverting the change I think it would rather make sense to change this line:
https://github.com/TuSimple/naive-ui/blob/c3b574863b9abefd9765a726b13b4a49fe5ae155/src/_internal/selection/src/styles/index.cssr.ts#L265

to:
```css
padding: 3px 7px 3px 0
```

This would ensure that the style variable is used and is consistent to the rest and it would ensure that there is a proper padding:
image

**Comment by kungege** [comment]
> 

@jaulz  hi 😊, as you see, when the `tag` wraps, the space between the `upper tag` and the `lower tag`  is 6px, I think this is not the result we want
image

**Comment by jaulz** [comment]
I would rather say that this is the correct behaviour because in my opinion each tag should have the height (including padding) of the element itself.

**Pull request closed without merging**
