### PR TITLE
feat: add color prop to Typography

### PR DESCRIPTION
**Pull request by jaulz**
This PR will add a `color` prop to the `Typography` components to support custom colors.

### CODE REVIEW

**Comment by 07akioni** [comment]
I prefer style if there's no nested DOM.

Add color may add api complexity.

**Comment by jaulz** [comment]
Hm, I just thought to make the API consistent and do not let the developer rely on setting a CSS variable whose name could change later. Having a dedicated prop would definitely make it future proof.

**Comment by 07akioni** [comment]
For components which already had `color` prop, most of them can't be directly styled by inline style, for example `button`, `progress`.

I think if the prop is not necessary, we prefer not adding it.

For example, long time ago, popover has `width` and `max-width` prop. However I found it can be achieved easily by `style`, so I removed it later.

**Comment by jaulz** [comment]
Okay, then I will close it for the time being 😊

**Pull request closed without merging**
