### PR TITLE
feat: expose useTheme and lightTheme

### PR DESCRIPTION
**Pull request by jaulz**
It would be great if the library could expose `useTheme` and `lightTheme` so it is easily possible to write custom components the same way as this library does.

### CODE REVIEW

**Comment by 07akioni** [comment]
Are you sure to do this? I can't figure a good scene for it. The built-in theme system is somehow complex for users and may be refactored after some time (although not in short term). Most of time `useThemeVars` is enough.

**Comment by jaulz** [comment]
@07akioni i would like to create a component that looks exactly like the Input component. Would you have any other good idea how to achieve it without copying styles? I wouldn't mind if we prefix the `useTheme` with an underscore to indicate that's it's internal and hence can change.

**Comment by 07akioni** [comment]
> @07akioni i would like to create a component that looks exactly like the Input component. Would you have any other good idea how to achieve it without copying styles? I wouldn't mind if we prefix the `useTheme` with an underscore to indicate that's it's internal and hence can change.

If so you would also need create css-render style for it, there would be a lot of work. So why don't you just import from library path like `naive-ui/es/_mixins/xxx`? I think export private API through index is not a good choice.

**Comment by jaulz** [comment]
You are right... I will try it another way first and will close this PR for the time being. Thanks for your input! 😊

**Pull request closed without merging**
